# Generated by Django 5.1.6 on 2025-02-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Shelter",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("capacity", models.IntegerField()),
                ("occupancy", models.IntegerField()),
            ],
        ),
    ]
